Uploading blueprint cloudify/aws.yaml...
 aws.yaml |############################################################| 100.0%
Blueprint uploaded. The blueprint's id is cloudify-wordpress-blueprint-aws
Creating new deployment from blueprint cloudify-wordpress-blueprint-aws...
Deployment created. The deployment's id is aws
Executing workflow `install` on deployment `aws` [timeout=900 seconds]
Deployment environment creation is pending...
2019-08-08 07:06:30.593  CFY <aws> Starting 'create_deployment_environment' workflow execution
2019-08-08 07:06:30.596  CFY <aws> Installing deployment and workflow plugins
2019-08-08 07:06:30.698  CFY <aws> Sending task 'cloudify_agent.operations.install_plugins'
2019-08-08 07:06:30.713  CFY <aws> Task started 'cloudify_agent.operations.install_plugins'
2019-08-08 07:06:31.040  LOG <aws> INFO: Installing plugin: cloudinit
2019-08-08 07:06:32.061  LOG <aws> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 07:06:32.062  LOG <aws> INFO: Installing plugin: ansible
2019-08-08 07:06:32.808  LOG <aws> INFO: Using existing installation of managed plugin: 7142c593-6e52-429a-8a71-55266c022e02 [package_name: cloudify-ansible-plugin, package_version: 2.4.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 07:06:32.808  LOG <aws> INFO: Installing plugin: aws
2019-08-08 07:06:33.801  LOG <aws> INFO: Using existing installation of managed plugin: 94ad4ec4-9c80-468a-a537-2ea42fe647ed [package_name: cloudify-aws-plugin, package_version: 2.3.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 07:06:33.802  LOG <aws> INFO: Installing plugin: suspend
2019-08-08 07:06:34.779  LOG <aws> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 07:06:34.780  LOG <aws> INFO: Installing plugin: configuration
2019-08-08 07:06:35.855  LOG <aws> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 07:06:35.855  LOG <aws> INFO: Installing plugin: scalelist
2019-08-08 07:06:36.887  LOG <aws> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 07:06:36.888  CFY <aws> Task succeeded 'cloudify_agent.operations.install_plugins'
2019-08-08 07:06:36.954  CFY <aws> Creating deployment work directory
2019-08-08 07:06:37.553  CFY <aws> 'create_deployment_environment' workflow execution succeeded
2019-08-08 07:06:42.248  CFY <aws> Starting 'install' workflow execution
2019-08-08 07:06:47.926  CFY <aws> [cloud_init_l7x4kk] Validating node instance before creation: nothing to do
2019-08-08 07:06:48.035  CFY <aws> [vpc_8npsfz] Validating node instance before creation: nothing to do
2019-08-08 07:06:48.150  CFY <aws> [cloud_init2_odyjbz] Validating node instance before creation: nothing to do
2019-08-08 07:06:48.240  CFY <aws> [ami_v6ewm7] Validating node instance before creation: nothing to do
2019-08-08 07:06:48.326  CFY <aws> [cloud_initdb_uxc7i4] Validating node instance before creation: nothing to do
2019-08-08 07:06:48.376  CFY <aws> [cloud_init_l7x4kk] Precreating node instance: nothing to do
2019-08-08 07:06:48.426  CFY <aws> [vpc_8npsfz] Precreating node instance: nothing to do
2019-08-08 07:06:48.478  CFY <aws> [cloud_init2_odyjbz] Precreating node instance: nothing to do
2019-08-08 07:06:48.530  CFY <aws> [cloud_initdb_uxc7i4] Precreating node instance: nothing to do
2019-08-08 07:06:48.577  CFY <aws> [ami_v6ewm7] Precreating node instance: nothing to do
2019-08-08 07:06:48.971  CFY <aws> [vpc_8npsfz] Creating node instance
2019-08-08 07:06:49.021  CFY <aws> [cloud_init_l7x4kk] Creating node instance
2019-08-08 07:06:49.187  CFY <aws> [vpc_8npsfz.create] Sending task 'cloudify_aws.ec2.resources.vpc.prepare'
2019-08-08 07:06:49.480  CFY <aws> [cloud_init2_odyjbz] Creating node instance
2019-08-08 07:06:49.528  CFY <aws> [cloud_initdb_uxc7i4] Creating node instance
2019-08-08 07:06:49.591  CFY <aws> [ami_v6ewm7] Creating node instance
2019-08-08 07:06:50.316  CFY <aws> [cloud_initdb_uxc7i4.create] Sending task 'cloudify_cloudinit.tasks.update'
2019-08-08 07:06:51.464  CFY <aws> [cloud_init_l7x4kk.create] Sending task 'cloudify_cloudinit.tasks.update'
2019-08-08 07:06:52.555  CFY <aws> [ami_v6ewm7.create] Sending task 'cloudify_aws.ec2.resources.image.prepare'
2019-08-08 07:06:53.210  CFY <aws> [vpc_8npsfz.create] Task succeeded 'cloudify_aws.ec2.resources.vpc.prepare'
2019-08-08 07:06:53.861  CFY <aws> [cloud_init2_odyjbz.create] Sending task 'cloudify_cloudinit.tasks.update'
2019-08-08 07:06:54.709  CFY <aws> [cloud_initdb_uxc7i4.create] Task succeeded 'cloudify_cloudinit.tasks.update'
2019-08-08 07:06:55.711  CFY <aws> [cloud_initdb_uxc7i4] Node instance created
2019-08-08 07:06:56.336  CFY <aws> [vpc_8npsfz] Node instance created
2019-08-08 07:06:56.399  CFY <aws> [cloud_init_l7x4kk.create] Task succeeded 'cloudify_cloudinit.tasks.update'
2019-08-08 07:06:56.488  CFY <aws> [cloud_initdb_uxc7i4] Configuring node instance
2019-08-08 07:06:57.093  CFY <aws> [cloud_init_l7x4kk] Node instance created
2019-08-08 07:06:57.294  CFY <aws> [cloud_initdb_uxc7i4.configure] Sending task 'cloudify_cloudinit.tasks.update'
2019-08-08 07:06:58.085  CFY <aws> [vpc_8npsfz] Configuring node instance
2019-08-08 07:06:58.714  CFY <aws> [vpc_8npsfz.configure] Sending task 'cloudify_aws.ec2.resources.vpc.create'
2019-08-08 07:06:58.995  CFY <aws> [cloud_init_l7x4kk] Configuring node instance
2019-08-08 07:06:59.252  CFY <aws> [cloud_init2_odyjbz.create] Task succeeded 'cloudify_cloudinit.tasks.update'
2019-08-08 07:06:59.838  CFY <aws> [cloud_init_l7x4kk.configure] Sending task 'cloudify_cloudinit.tasks.update'
2019-08-08 07:07:00.223  CFY <aws> [cloud_init2_odyjbz] Node instance created
2019-08-08 07:07:00.439  CFY <aws> [ami_v6ewm7.create] Task succeeded 'cloudify_aws.ec2.resources.image.prepare'
2019-08-08 07:07:01.644  CFY <aws> [cloud_init2_odyjbz] Configuring node instance
2019-08-08 07:07:02.340  CFY <aws> [ami_v6ewm7] Node instance created
2019-08-08 07:07:02.796  CFY <aws> [cloud_init2_odyjbz.configure] Sending task 'cloudify_cloudinit.tasks.update'
2019-08-08 07:07:03.214  CFY <aws> [cloud_initdb_uxc7i4.configure] Task succeeded 'cloudify_cloudinit.tasks.update'
2019-08-08 07:07:04.019  CFY <aws> [ami_v6ewm7] Configuring node instance: nothing to do
2019-08-08 07:07:04.194  CFY <aws> [cloud_initdb_uxc7i4] Node instance configured
2019-08-08 07:07:04.906  CFY <aws> [ami_v6ewm7] Starting node instance: nothing to do
2019-08-08 07:07:05.142  CFY <aws> [cloud_initdb_uxc7i4] Starting node instance
2019-08-08 07:07:05.989  CFY <aws> [ami_v6ewm7] Poststarting node instance: nothing to do
2019-08-08 07:07:06.235  CFY <aws> [cloud_initdb_uxc7i4.start] Sending task 'cloudify_cloudinit.tasks.update'
2019-08-08 07:07:06.320  CFY <aws> [cloud_init_l7x4kk.configure] Task succeeded 'cloudify_cloudinit.tasks.update'
2019-08-08 07:07:07.168  CFY <aws> [vpc_8npsfz.configure] Task succeeded 'cloudify_aws.ec2.resources.vpc.create'
2019-08-08 07:07:07.725  CFY <aws> [cloud_init2_odyjbz.configure] Task succeeded 'cloudify_cloudinit.tasks.update'
2019-08-08 07:07:08.363  CFY <aws> [vpc_8npsfz] Node instance configured
2019-08-08 07:07:08.483  CFY <aws> [cloud_init_l7x4kk] Node instance configured
2019-08-08 07:07:08.945  CFY <aws> [ami_v6ewm7] Node instance started
2019-08-08 07:07:09.428  CFY <aws> [cloud_init2_odyjbz] Node instance configured
2019-08-08 07:07:09.992  CFY <aws> [cloud_init_l7x4kk] Starting node instance
2019-08-08 07:07:10.141  CFY <aws> [vpc_8npsfz] Starting node instance: nothing to do
2019-08-08 07:07:10.414  CFY <aws> [cloud_init_l7x4kk.start] Sending task 'cloudify_cloudinit.tasks.update'
2019-08-08 07:07:10.439  CFY <aws> [cloud_init2_odyjbz] Starting node instance
2019-08-08 07:07:10.978  CFY <aws> [cloud_initdb_uxc7i4.start] Task succeeded 'cloudify_cloudinit.tasks.update'
2019-08-08 07:07:11.688  CFY <aws> [vpc_8npsfz] Poststarting node instance: nothing to do
2019-08-08 07:07:11.873  CFY <aws> [cloud_init2_odyjbz.start] Sending task 'cloudify_cloudinit.tasks.update'
2019-08-08 07:07:12.770  CFY <aws> [cloud_initdb_uxc7i4] Poststarting node instance: nothing to do
2019-08-08 07:07:12.992  CFY <aws> [vpc_8npsfz] Node instance started
2019-08-08 07:07:14.397  CFY <aws> [cloud_initdb_uxc7i4] Node instance started
2019-08-08 07:07:14.808  CFY <aws> [cloud_init_l7x4kk.start] Task succeeded 'cloudify_cloudinit.tasks.update'
2019-08-08 07:07:16.018  CFY <aws> [cloud_init_l7x4kk] Poststarting node instance: nothing to do
2019-08-08 07:07:16.148  CFY <aws> [subnet_exxx3x] Validating node instance before creation: nothing to do
2019-08-08 07:07:16.351  CFY <aws> [internet_gateway_bk4lve] Validating node instance before creation: nothing to do
2019-08-08 07:07:16.485  CFY <aws> [security_group_72rav1] Validating node instance before creation: nothing to do
2019-08-08 07:07:16.937  CFY <aws> [cloud_init_l7x4kk] Node instance started
2019-08-08 07:07:17.017  CFY <aws> [subnet_exxx3x] Precreating node instance: nothing to do
2019-08-08 07:07:17.131  CFY <aws> [internet_gateway_bk4lve] Precreating node instance: nothing to do
2019-08-08 07:07:17.282  CFY <aws> [security_group_72rav1] Precreating node instance: nothing to do
2019-08-08 07:07:17.397  CFY <aws> [subnet_exxx3x] Creating node instance
2019-08-08 07:07:17.455  CFY <aws> [cloud_init2_odyjbz.start] Task succeeded 'cloudify_cloudinit.tasks.update'
2019-08-08 07:07:17.885  CFY <aws> [subnet_exxx3x.create] Sending task 'cloudify_aws.ec2.resources.subnet.prepare'
2019-08-08 07:07:18.040  CFY <aws> [internet_gateway_bk4lve] Creating node instance
2019-08-08 07:07:18.619  CFY <aws> [security_group_72rav1] Creating node instance
2019-08-08 07:07:18.686  CFY <aws> [cloud_init2_odyjbz] Poststarting node instance: nothing to do
2019-08-08 07:07:19.070  CFY <aws> [cloud_init2_odyjbz] Node instance started
2019-08-08 07:07:19.194  CFY <aws> [security_group_72rav1.create] Sending task 'cloudify_aws.ec2.resources.securitygroup.prepare'
2019-08-08 07:07:20.316  CFY <aws> [internet_gateway_bk4lve.create] Sending task 'cloudify_aws.ec2.resources.internet_gateway.prepare'
2019-08-08 07:07:23.998  CFY <aws> [subnet_exxx3x.create] Task succeeded 'cloudify_aws.ec2.resources.subnet.prepare'
2019-08-08 07:07:24.476  CFY <aws> [subnet_exxx3x] Node instance created
2019-08-08 07:07:24.631  CFY <aws> [subnet_exxx3x] Configuring node instance
2019-08-08 07:07:25.427  CFY <aws> [subnet_exxx3x.configure] Sending task 'cloudify_aws.ec2.resources.subnet.create'
2019-08-08 07:07:25.857  CFY <aws> [security_group_72rav1.create] Task succeeded 'cloudify_aws.ec2.resources.securitygroup.prepare'
2019-08-08 07:07:26.271  CFY <aws> [internet_gateway_bk4lve.create] Task succeeded 'cloudify_aws.ec2.resources.internet_gateway.prepare'
2019-08-08 07:07:26.568  CFY <aws> [internet_gateway_bk4lve] Node instance created
2019-08-08 07:07:26.927  CFY <aws> [security_group_72rav1] Node instance created
2019-08-08 07:07:27.532  CFY <aws> [security_group_72rav1] Configuring node instance
2019-08-08 07:07:27.950  CFY <aws> [security_group_72rav1.configure] Sending task 'cloudify_aws.ec2.resources.securitygroup.create'
2019-08-08 07:07:27.981  CFY <aws> [internet_gateway_bk4lve] Configuring node instance
2019-08-08 07:07:29.041  CFY <aws> [internet_gateway_bk4lve.configure] Sending task 'cloudify_aws.ec2.resources.internet_gateway.create'
2019-08-08 07:07:30.563  CFY <aws> [subnet_exxx3x.configure] Task failed 'cloudify_aws.ec2.resources.subnet.create' -> An error occurred (InvalidParameterValue) when calling the CreateSubnet operation: Value (sa-east-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: sa-east-1a, sa-east-1c.
Causes (most recent cause last):
--------------------------------
Traceback (most recent call last):
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/__init__.py", line 87, in make_client_call
    res = client_method(**client_method_args)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidParameterValue) when calling the CreateSubnet operation: Value (sa-east-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: sa-east-1a, sa-east-1c.
--------------------------------
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 303, in wrapper_inner
    result = function(**kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 330, in wrapper_inner
    fail_on_missing)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 52, in _wait_for_status
    function(**kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 458, in wrapper
    result = fn(**kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/ec2/resources/subnet.py", line 146, in create
    create_response = iface.create(params)[SUBNET]
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/ec2/resources/subnet.py", line 72, in create
    return self.make_client_call('create_subnet', params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/__init__.py", line 96, in make_client_call
    causes=[exception_to_error_cause(error, tb)])
NonRecoverableError: An error occurred (InvalidParameterValue) when calling the CreateSubnet operation: Value (sa-east-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: sa-east-1a, sa-east-1c.

2019-08-08 07:07:33.064  CFY <aws> [security_group_72rav1.configure] Task succeeded 'cloudify_aws.ec2.resources.securitygroup.create'
2019-08-08 07:07:33.490  CFY <aws> [internet_gateway_bk4lve.configure] Task succeeded 'cloudify_aws.ec2.resources.internet_gateway.create'
2019-08-08 07:07:33.594  CFY <aws> 'install' workflow execution failed: RuntimeError: Workflow failed: Task failed 'cloudify_aws.ec2.resources.subnet.create' -> An error occurred (InvalidParameterValue) when calling the CreateSubnet operation: Value (sa-east-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: sa-east-1a, sa-east-1c.
Execution of workflow install for deployment aws failed. [error=Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 664, in _remote_workflow_child_thread
    workflow_result = self._execute_workflow_function()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 693, in _execute_workflow_function
    result = self.func(*self.args, **self.kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/workflows.py", line 31, in install
    node_instances=set(ctx.node_instances))
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 29, in install_node_instances
    processor.install()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 102, in install
    graph.execute()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/workflows/tasks_graph.py", line 237, in execute
    raise self._error
RuntimeError: Workflow failed: Task failed 'cloudify_aws.ec2.resources.subnet.create' -> An error occurred (InvalidParameterValue) when calling the CreateSubnet operation: Value (sa-east-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: sa-east-1a, sa-east-1c.
]
* Run 'cfy events list e6bd3837-97f5-4339-ab7c-0295f60a9e1d' to retrieve the execution's events/logs
'Executing workflow `uninstall` on deployment `aws` [timeout=900 seconds] 2019-08-08 07:02:03.239 CFY <aws> Starting 'uninstall' workflow execution 2019-08-08 07:02:11.070 CFY <aws> [config-database_r8chl4] Stopping node instance 2019-08-08 07:02:11.228 CFY <aws> [ipdb_pk7zes] Stopping node instance 2019-08-08 07:02:11.308 CFY <aws> [ip2_xl0p52] Stopping node instance 2019-08-08 07:02:11.369 CFY <aws> [security_group_rules_4myi97] Stopping node instance 2019-08-08 07:02:11.448 CFY <aws> [config-wordpress2_i8bb4o] Stopping node instance 2019-08-08 07:02:11.699 CFY <aws> [ip1_u0wro0] Stopping node instance 2019-08-08 07:02:12.363 CFY <aws> [config-wordpress1_sivnp2] Stopping node instance 2019-08-08 07:02:12.682 CFY <aws> [route_public_subnet_internet_gateway_wlw34e] Stopping node instance 2019-08-08 07:02:12.943 CFY <aws> [config-database_r8chl4] Validating node instance after deletion: nothing to do 2019-08-08 07:02:13.003 CFY <aws> [config-wordpress2_i8bb4o] Validating node instance after deletion: nothing to do 2019-08-08 07:02:13.071 CFY <aws> [ip2_xl0p52] Validating node instance after deletion: nothing to do 2019-08-08 07:02:13.129 CFY <aws> [ip1_u0wro0] Validating node instance after deletion: nothing to do 2019-08-08 07:02:13.186 CFY <aws> [config-wordpress1_sivnp2] Validating node instance after deletion: nothing to do 2019-08-08 07:02:13.286 CFY <aws> [security_group_rules_4myi97] Validating node instance after deletion: nothing to do 2019-08-08 07:02:13.484 CFY <aws> [route_public_subnet_internet_gateway_wlw34e] Validating node instance after deletion: nothing to do 2019-08-08 07:02:13.525 CFY <aws> [ip2_xl0p52.stop] Sending task 'cloudify_aws.ec2.resources.elasticip.detach' 2019-08-08 07:02:13.658 CFY <aws> [config-database_r8chl4] Stopped node instance: nothing to do 2019-08-08 07:02:13.780 CFY <aws> [ipdb_pk7zes] Validating node instance after deletion: nothing to do 2019-08-08 07:02:13.891 CFY <aws> [config-wordpress2_i8bb4o] Stopped node instance: nothing to do 2019-08-08 07:02:14.484 CFY <aws> [ip1_u0wro0.stop] Sending task 'cloudify_aws.ec2.resources.elasticip.detach' 2019-08-08 07:02:15.700 CFY <aws> [security_group_rules_4myi97.stop] Sending task 'cloudify_aws.ec2.resources.securitygroup.revoke_ingress_rules' 2019-08-08 07:02:16.796 CFY <aws> [config-wordpress1_sivnp2] Stopped node instance: nothing to do 2019-08-08 07:02:16.980 CFY <aws> [ipdb_pk7zes.stop] Sending task 'cloudify_aws.ec2.resources.elasticip.detach' 2019-08-08 07:02:19.218 CFY <aws> [route_public_subnet_internet_gateway_wlw34e] Stopped node instance: nothing to do 2019-08-08 07:02:19.546 CFY <aws> [config-wordpress2_i8bb4o] Unlinking relationships 2019-08-08 07:02:20.468 CFY <aws> [ip2_xl0p52.stop] Task succeeded 'cloudify_aws.ec2.resources.elasticip.detach' 2019-08-08 07:02:20.502 CFY <aws> [config-wordpress2_i8bb4o->vm-app2_p0gi40|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 07:02:20.774 CFY <aws> [config-database_r8chl4] Unlinking relationships 2019-08-08 07:02:22.055 CFY <aws> [config-database_r8chl4->vm-database_pb2cgj|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 07:02:22.132 CFY <aws> [config-wordpress1_sivnp2] Unlinking relationships 2019-08-08 07:02:23.339 CFY <aws> [ip2_xl0p52] Stopped node instance 2019-08-08 07:02:23.800 CFY <aws> [route_public_subnet_internet_gateway_wlw34e] Unlinking relationships 2019-08-08 07:02:24.150 CFY <aws> [config-wordpress1_sivnp2->vm-app1_vw1ei3|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 07:02:25.778 CFY <aws> [ip2_xl0p52] Unlinking relationships 2019-08-08 07:02:25.981 CFY <aws> [ip1_u0wro0.stop] Task succeeded 'cloudify_aws.ec2.resources.elasticip.detach' 2019-08-08 07:02:26.330 CFY <aws> [route_public_subnet_internet_gateway_wlw34e] Relationships unlinked 2019-08-08 07:02:26.758 CFY <aws> [ip1_u0wro0] Stopped node instance 2019-08-08 07:02:28.014 CFY <aws> [route_public_subnet_internet_gateway_wlw34e] Deleting node instance 2019-08-08 07:02:28.284 CFY <aws> [security_group_rules_4myi97.stop] Task succeeded 'cloudify_aws.ec2.resources.securitygroup.revoke_ingress_rules' 2019-08-08 07:02:28.316 CFY <aws> [ip2_xl0p52] Relationships unlinked 2019-08-08 07:02:29.020 CFY <aws> [route_public_subnet_internet_gateway_wlw34e.delete] Sending task 'cloudify_aws.ec2.resources.route.delete' 2019-08-08 07:02:29.823 CFY <aws> [security_group_rules_4myi97] Stopped node instance 2019-08-08 07:02:30.428 CFY <aws> [config-wordpress2_i8bb4o->vm-app2_p0gi40|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 07:02:31.261 CFY <aws> [ipdb_pk7zes.stop] Task succeeded 'cloudify_aws.ec2.resources.elasticip.detach' 2019-08-08 07:02:31.755 CFY <aws> [ip1_u0wro0] Unlinking relationships 2019-08-08 07:02:32.011 CFY <aws> [ip2_xl0p52] Deleting node instance 2019-08-08 07:02:33.003 CFY <aws> [ip2_xl0p52.delete] Sending task 'cloudify_aws.ec2.resources.elasticip.delete' 2019-08-08 07:02:33.312 CFY <aws> [config-wordpress2_i8bb4o] Relationships unlinked 2019-08-08 07:02:33.493 CFY <aws> [ipdb_pk7zes] Stopped node instance 2019-08-08 07:02:33.538 CFY <aws> [config-database_r8chl4->vm-database_pb2cgj|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 07:02:34.104 CFY <aws> [ip1_u0wro0] Relationships unlinked 2019-08-08 07:02:34.431 CFY <aws> [security_group_rules_4myi97] Unlinking relationships 2019-08-08 07:02:34.675 CFY <aws> [config-wordpress1_sivnp2->vm-app1_vw1ei3|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 07:02:35.551 CFY <aws> [config-wordpress2_i8bb4o] Deleting node instance: nothing to do 2019-08-08 07:02:35.701 CFY <aws> [config-database_r8chl4] Relationships unlinked 2019-08-08 07:02:36.392 CFY <aws> [ip1_u0wro0] Deleting node instance 2019-08-08 07:02:36.521 CFY <aws> [config-wordpress1_sivnp2] Relationships unlinked 2019-08-08 07:02:36.742 CFY <aws> [security_group_rules_4myi97] Relationships unlinked 2019-08-08 07:02:36.843 CFY <aws> [ip1_u0wro0.delete] Sending task 'cloudify_aws.ec2.resources.elasticip.delete' 2019-08-08 07:02:36.955 CFY <aws> [ipdb_pk7zes] Unlinking relationships 2019-08-08 07:02:37.144 CFY <aws> [config-wordpress2_i8bb4o] Deleted node instance 2019-08-08 07:02:37.831 CFY <aws> [config-database_r8chl4] Deleting node instance: nothing to do 2019-08-08 07:02:38.214 CFY <aws> [config-database_r8chl4] Deleted node instance 2019-08-08 07:02:39.465 CFY <aws> [security_group_rules_4myi97] Deleting node instance: nothing to do 2019-08-08 07:02:39.819 CFY <aws> [config-wordpress1_sivnp2] Deleting node instance: nothing to do 2019-08-08 07:02:40.136 CFY <aws> [ipdb_pk7zes] Relationships unlinked 2019-08-08 07:02:40.941 CFY <aws> [route_public_subnet_internet_gateway_wlw34e.delete] Task succeeded 'cloudify_aws.ec2.resources.route.delete' 2019-08-08 07:02:41.278 CFY <aws> [vm-app2_p0gi40] Stopping node instance 2019-08-08 07:02:41.385 CFY <aws> [vm-database_pb2cgj] Stopping node instance 2019-08-08 07:02:41.540 CFY <aws> [security_group_rules_4myi97] Deleted node instance 2019-08-08 07:02:42.271 CFY <aws> [config-wordpress1_sivnp2] Deleted node instance 2019-08-08 07:02:43.393 CFY <aws> [ip2_xl0p52.delete] Task succeeded 'cloudify_aws.ec2.resources.elasticip.delete' 2019-08-08 07:02:43.763 CFY <aws> [ipdb_pk7zes] Deleting node instance 2019-08-08 07:02:44.211 CFY <aws> [ipdb_pk7zes.delete] Sending task 'cloudify_aws.ec2.resources.elasticip.delete' 2019-08-08 07:02:44.519 CFY <aws> [route_public_subnet_internet_gateway_wlw34e] Deleted node instance 2019-08-08 07:02:44.596 CFY <aws> [vm-app2_p0gi40] Validating node instance after deletion: nothing to do 2019-08-08 07:02:44.662 CFY <aws> [vm-database_pb2cgj] Validating node instance after deletion: nothing to do 2019-08-08 07:02:44.747 CFY <aws> [ip2_xl0p52] Deleted node instance 2019-08-08 07:02:45.504 CFY <aws> [vm-app1_vw1ei3] Stopping node instance 2019-08-08 07:02:45.818 CFY <aws> [vm-app1_vw1ei3] Validating node instance after deletion: nothing to do 2019-08-08 07:02:46.569 CFY <aws> [vm-app2_p0gi40.stop] Sending task 'cloudify_aws.ec2.resources.instances.stop' 2019-08-08 07:02:47.016 CFY <aws> [internet_gateway_rw1isn] Stopping node instance 2019-08-08 07:02:47.093 CFY <aws> [ip1_u0wro0.delete] Task succeeded 'cloudify_aws.ec2.resources.elasticip.delete' 2019-08-08 07:02:47.166 CFY <aws> [routetable_lg05iv] Stopping node instance 2019-08-08 07:02:47.866 CFY <aws> [vm-database_pb2cgj.stop] Sending task 'cloudify_aws.ec2.resources.instances.stop' 2019-08-08 07:02:49.296 CFY <aws> [vm-app1_vw1ei3.stop] Sending task 'cloudify_aws.ec2.resources.instances.stop' 2019-08-08 07:02:49.608 CFY <aws> [routetable_lg05iv] Validating node instance after deletion: nothing to do 2019-08-08 07:02:49.844 CFY <aws> [ip1_u0wro0] Deleted node instance 2019-08-08 07:02:50.057 CFY <aws> [internet_gateway_rw1isn] Validating node instance after deletion: nothing to do 2019-08-08 07:02:50.746 CFY <aws> [routetable_lg05iv.stop] Sending task 'cloudify_aws.ec2.resources.routetable.detach' 2019-08-08 07:02:52.216 CFY <aws> [internet_gateway_rw1isn.stop] Sending task 'cloudify_aws.ec2.resources.internet_gateway.detach' 2019-08-08 07:02:53.275 CFY <aws> [ipdb_pk7zes.delete] Task succeeded 'cloudify_aws.ec2.resources.elasticip.delete' 2019-08-08 07:02:53.463 CFY <aws> [ipdb_pk7zes] Deleted node instance 2019-08-08 07:02:57.913 CFY <aws> [vm-app2_p0gi40.stop] Task rescheduled 'cloudify_aws.ec2.resources.instances.stop' -> EC2 Instances ID# "i-06cc8896dfad646e0" is still in a pending state. Traceback (most recent call last): File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main payload = handler.handle() File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle result = self._run_operation_func(ctx, kwargs) File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func return self.func(*self.args, **kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 303, in wrapper_inner result = function(**kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 330, in wrapper_inner fail_on_missing) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 76, in _wait_for_status % (resource_type, iface.resource_id)) OperationRetry: EC2 Instances ID# "i-06cc8896dfad646e0" is still in a pending state. 2019-08-08 07:02:59.768 CFY <aws> [vm-database_pb2cgj.stop] Task rescheduled 'cloudify_aws.ec2.resources.instances.stop' -> EC2 Instances ID# "i-042527e655a8d07f3" is still in a pending state. Traceback (most recent call last): File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main payload = handler.handle() File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle result = self._run_operation_func(ctx, kwargs) File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func return self.func(*self.args, **kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 303, in wrapper_inner result = function(**kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 330, in wrapper_inner fail_on_missing) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 76, in _wait_for_status % (resource_type, iface.resource_id)) OperationRetry: EC2 Instances ID# "i-042527e655a8d07f3" is still in a pending state. 2019-08-08 07:03:00.798 CFY <aws> [vm-app1_vw1ei3.stop] Task rescheduled 'cloudify_aws.ec2.resources.instances.stop' -> EC2 Instances ID# "i-04823762a0cc46f77" is still in a pending state. Traceback (most recent call last): File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main payload = handler.handle() File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle result = self._run_operation_func(ctx, kwargs) File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func return self.func(*self.args, **kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 303, in wrapper_inner result = function(**kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 330, in wrapper_inner fail_on_missing) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 76, in _wait_for_status % (resource_type, iface.resource_id)) OperationRetry: EC2 Instances ID# "i-04823762a0cc46f77" is still in a pending state. 2019-08-08 07:03:00.933 CFY <aws> [routetable_lg05iv.stop] Task succeeded 'cloudify_aws.ec2.resources.routetable.detach' 2019-08-08 07:03:01.048 CFY <aws> [routetable_lg05iv] Stopped node instance 2019-08-08 07:03:01.544 CFY <aws> [routetable_lg05iv] Unlinking relationships 2019-08-08 07:03:01.558 CFY <aws> [internet_gateway_rw1isn.stop] Task succeeded 'cloudify_aws.ec2.resources.internet_gateway.detach' 2019-08-08 07:03:01.716 CFY <aws> [internet_gateway_rw1isn] Stopped node instance 2019-08-08 07:03:02.075 CFY <aws> [routetable_lg05iv] Relationships unlinked 2019-08-08 07:03:02.365 CFY <aws> [routetable_lg05iv] Deleting node instance 2019-08-08 07:03:02.618 CFY <aws> [internet_gateway_rw1isn] Unlinking relationships 2019-08-08 07:03:02.725 CFY <aws> [routetable_lg05iv.delete] Sending task 'cloudify_aws.ec2.resources.routetable.delete' 2019-08-08 07:03:03.947 CFY <aws> [internet_gateway_rw1isn] Relationships unlinked 2019-08-08 07:03:04.588 CFY <aws> [internet_gateway_rw1isn] Deleting node instance 2019-08-08 07:03:04.870 CFY <aws> [internet_gateway_rw1isn.delete] Sending task 'cloudify_aws.ec2.resources.internet_gateway.delete' 2019-08-08 07:03:07.942 CFY <aws> [routetable_lg05iv.delete] Task succeeded 'cloudify_aws.ec2.resources.routetable.delete' 2019-08-08 07:03:08.403 CFY <aws> [routetable_lg05iv] Deleted node instance 2019-08-08 07:03:10.372 CFY <aws> [internet_gateway_rw1isn.delete] Task succeeded 'cloudify_aws.ec2.resources.internet_gateway.delete' 2019-08-08 07:03:10.600 CFY <aws> [internet_gateway_rw1isn] Deleted node instance 2019-08-08 07:03:13.175 CFY <aws> [vm-app2_p0gi40.stop] Sending task 'cloudify_aws.ec2.resources.instances.stop' [retry 1/60] 2019-08-08 07:03:14.969 CFY <aws> [vm-database_pb2cgj.stop] Sending task 'cloudify_aws.ec2.resources.instances.stop' [retry 1/60] 2019-08-08 07:03:16.040 CFY <aws> [vm-app1_vw1ei3.stop] Sending task 'cloudify_aws.ec2.resources.instances.stop' [retry 1/60] 2019-08-08 07:03:18.149 CFY <aws> [vm-app2_p0gi40.stop] Task succeeded 'cloudify_aws.ec2.resources.instances.stop' [retry 1/60] 2019-08-08 07:03:18.196 CFY <aws> [vm-app2_p0gi40] Stopped node instance 2019-08-08 07:03:19.143 CFY <aws> [vm-app2_p0gi40] Unlinking relationships 2019-08-08 07:03:19.755 CFY <aws> [vm-app2_p0gi40] Relationships unlinked 2019-08-08 07:03:20.090 CFY <aws> [vm-app2_p0gi40] Deleting node instance 2019-08-08 07:03:20.792 CFY <aws> [vm-app2_p0gi40.delete] Sending task 'cloudify_aws.ec2.resources.instances.delete' 2019-08-08 07:03:21.403 CFY <aws> [vm-database_pb2cgj.stop] Task succeeded 'cloudify_aws.ec2.resources.instances.stop' [retry 1/60] 2019-08-08 07:03:21.976 CFY <aws> [vm-database_pb2cgj] Stopped node instance 2019-08-08 07:03:22.908 CFY <aws> [vm-database_pb2cgj] Unlinking relationships 2019-08-08 07:03:23.293 CFY <aws> [vm-app1_vw1ei3.stop] Task succeeded 'cloudify_aws.ec2.resources.instances.stop' [retry 1/60] 2019-08-08 07:03:23.416 CFY <aws> [vm-app1_vw1ei3] Stopped node instance 2019-08-08 07:03:24.229 CFY <aws> [vm-database_pb2cgj] Relationships unlinked 2019-08-08 07:03:27.066 CFY <aws> [vm-database_pb2cgj] Deleting node instance 2019-08-08 07:03:27.242 CFY <aws> [vm-app1_vw1ei3] Unlinking relationships 2019-08-08 07:03:27.621 CFY <aws> [vm-database_pb2cgj.delete] Sending task 'cloudify_aws.ec2.resources.instances.delete' 2019-08-08 07:03:29.044 CFY <aws> [vm-app1_vw1ei3] Relationships unlinked 2019-08-08 07:03:29.752 CFY <aws> [vm-app1_vw1ei3] Deleting node instance 2019-08-08 07:03:30.266 CFY <aws> [vm-app1_vw1ei3.delete] Sending task 'cloudify_aws.ec2.resources.instances.delete' 2019-08-08 07:03:31.206 CFY <aws> [vm-app2_p0gi40.delete] Task rescheduled 'cloudify_aws.ec2.resources.instances.delete' -> EC2 Instances ID# "i-06cc8896dfad646e0" is still in a pending state. Traceback (most recent call last): File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main payload = handler.handle() File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle result = self._run_operation_func(ctx, kwargs) File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func return self.func(*self.args, **kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 303, in wrapper_inner result = function(**kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 382, in wrapper_inner % (resource_type, iface.resource_id)) OperationRetry: EC2 Instances ID# "i-06cc8896dfad646e0" is still in a pending state. 2019-08-08 07:03:34.052 CFY <aws> [vm-database_pb2cgj.delete] Task rescheduled 'cloudify_aws.ec2.resources.instances.delete' -> EC2 Instances ID# "i-042527e655a8d07f3" is still in a pending state. Traceback (most recent call last): File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main payload = handler.handle() File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle result = self._run_operation_func(ctx, kwargs) File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func return self.func(*self.args, **kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 303, in wrapper_inner result = function(**kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 382, in wrapper_inner % (resource_type, iface.resource_id)) OperationRetry: EC2 Instances ID# "i-042527e655a8d07f3" is still in a pending state. 2019-08-08 07:03:35.794 CFY <aws> [vm-app1_vw1ei3.delete] Task rescheduled 'cloudify_aws.ec2.resources.instances.delete' -> EC2 Instances ID# "i-04823762a0cc46f77" is still in a pending state. Traceback (most recent call last): File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main payload = handler.handle() File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle result = self._run_operation_func(ctx, kwargs) File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func return self.func(*self.args, **kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 303, in wrapper_inner result = function(**kwargs) File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-aws-plugin-2.3.0/lib/python2.7/site-packages/cloudify_aws/common/decorators.py", line 382, in wrapper_inner % (resource_type, iface.resource_id)) OperationRetry: EC2 Instances ID# "i-04823762a0cc46f77" is still in a pending state. 2019-08-08 07:03:46.273 CFY <aws> [vm-app2_p0gi40.delete] Sending task 'cloudify_aws.ec2.resources.instances.delete' [retry 1/60] 2019-08-08 07:03:49.158 CFY <aws> [vm-database_pb2cgj.delete] Sending task 'cloudify_aws.ec2.resources.instances.delete' [retry 1/60] 2019-08-08 07:03:49.921 CFY <aws> [vm-app2_p0gi40.delete] Task succeeded 'cloudify_aws.ec2.resources.instances.delete' [retry 1/60] 2019-08-08 07:03:50.354 CFY <aws> [vm-app2_p0gi40] Deleted node instance 2019-08-08 07:03:50.731 CFY <aws> [cloud_init2_e6blw1] Stopping node instance 2019-08-08 07:03:50.901 CFY <aws> [nic2_ao90em] Stopping node instance 2019-08-08 07:03:51.285 CFY <aws> [vm-app1_vw1ei3.delete] Sending task 'cloudify_aws.ec2.resources.instances.delete' [retry 1/60] 2019-08-08 07:03:52.279 CFY <aws> [nic2_ao90em] Validating node instance after deletion: nothing to do 2019-08-08 07:03:52.457 CFY <aws> [cloud_init2_e6blw1] Validating node instance after deletion: nothing to do 2019-08-08 07:03:52.691 CFY <aws> [nic2_ao90em.stop] Sending task 'cloudify_aws.ec2.resources.eni.detach' 2019-08-08 07:03:53.919 CFY <aws> [cloud_init2_e6blw1.stop] Sending task 'cloudify_cloudinit.tasks.update' 2019-08-08 07:03:54.779 CFY <aws> [vm-database_pb2cgj.delete] Task succeeded 'cloudify_aws.ec2.resources.instances.delete' [retry 1/60] 2019-08-08 07:03:55.568 CFY <aws> [vm-database_pb2cgj] Deleted node instance 2019-08-08 07:03:56.999 CFY <aws> [nicdb_8id1l8] Stopping node instance 2019-08-08 07:03:57.569 CFY <aws> [cloud_initdb_nt7yiq] Stopping node instance 2019-08-08 07:03:57.684 CFY <aws> [vm-app1_vw1ei3.delete] Task succeeded 'cloudify_aws.ec2.resources.instances.delete' [retry 1/60] 2019-08-08 07:03:57.733 CFY <aws> [nicdb_8id1l8] Validating node instance after deletion: nothing to do 2019-08-08 07:03:57.874 CFY <aws> [vm-app1_vw1ei3] Deleted node instance 2019-08-08 07:03:58.132 CFY <aws> [nicdb_8id1l8.stop] Sending task 'cloudify_aws.ec2.resources.eni.detach' 2019-08-08 07:03:58.568 CFY <aws> [cloud_initdb_nt7yiq] Validating node instance after deletion: nothing to do 2019-08-08 07:03:59.384 CFY <aws> [cloud_init2_e6blw1.stop] Task succeeded 'cloudify_cloudinit.tasks.update' 2019-08-08 07:03:59.620 CFY <aws> [cloud_initdb_nt7yiq.stop] Sending task 'cloudify_cloudinit.tasks.update' 2019-08-08 07:03:59.642 CFY <aws> [nic2_ao90em.stop] Task succeeded 'cloudify_aws.ec2.resources.eni.detach' 2019-08-08 07:04:00.524 CFY <aws> [cloud_init2_e6blw1] Stopped node instance 2019-08-08 07:04:00.782 CFY <aws> [nic2_ao90em] Stopped node instance 2019-08-08 07:04:00.962 CFY <aws> [ami_vtkjbi] Stopping node instance 2019-08-08 07:04:01.555 CFY <aws> [nic1_vixg0u] Stopping node instance 2019-08-08 07:04:02.111 CFY <aws> [cloud_init_k8xkrm] Stopping node instance 2019-08-08 07:04:03.337 CFY <aws> [ami_vtkjbi] Validating node instance after deletion: nothing to do 2019-08-08 07:04:03.445 CFY <aws> [nicdb_8id1l8.stop] Task succeeded 'cloudify_aws.ec2.resources.eni.detach' 2019-08-08 07:04:03.527 CFY <aws> [nic1_vixg0u] Validating node instance after deletion: nothing to do 2019-08-08 07:04:03.699 CFY <aws> [cloud_init_k8xkrm] Validating node instance after deletion: nothing to do 2019-08-08 07:04:03.858 CFY <aws> [nic2_ao90em] Unlinking relationships 2019-08-08 07:04:03.972 CFY <aws> [nic1_vixg0u.stop] Sending task 'cloudify_aws.ec2.resources.eni.detach' 2019-08-08 07:04:04.023 CFY <aws> [cloud_init2_e6blw1] Unlinking relationships 2019-08-08 07:04:04.092 CFY <aws> [nicdb_8id1l8] Stopped node instance 2019-08-08 07:04:04.273 CFY <aws> [ami_vtkjbi] Stopped node instance: nothing to do 2019-08-08 07:04:04.468 CFY <aws> [cloud_initdb_nt7yiq.stop] Task succeeded 'cloudify_cloudinit.tasks.update' 2019-08-08 07:04:05.301 CFY <aws> [cloud_init_k8xkrm.stop] Sending task 'cloudify_cloudinit.tasks.update' 2019-08-08 07:04:06.691 CFY <aws> [cloud_initdb_nt7yiq] Stopped node instance 2019-08-08 07:04:06.832 CFY <aws> [ami_vtkjbi] Unlinking relationships 2019-08-08 07:04:07.061 CFY <aws> [cloud_init2_e6blw1] Relationships unlinked 2019-08-08 07:04:07.365 CFY <aws> [nic2_ao90em] Relationships unlinked 2019-08-08 07:04:07.586 CFY <aws> [nicdb_8id1l8] Unlinking relationships 2019-08-08 07:04:08.636 CFY <aws> [ami_vtkjbi] Relationships unlinked 2019-08-08 07:04:08.744 CFY <aws> [cloud_init2_e6blw1] Deleting node instance 2019-08-08 07:04:08.859 CFY <aws> [nic2_ao90em] Deleting node instance 2019-08-08 07:04:09.161 CFY <aws> [cloud_init2_e6blw1.delete] Sending task 'cloudify_cloudinit.tasks.update' 2019-08-08 07:04:09.266 CFY <aws> [nic1_vixg0u.stop] Task succeeded 'cloudify_aws.ec2.resources.eni.detach' 2019-08-08 07:04:09.350 CFY <aws> [nicdb_8id1l8] Relationships unlinked 2019-08-08 07:04:09.450 CFY <aws> [cloud_initdb_nt7yiq] Unlinking relationships 2019-08-08 07:04:09.589 CFY <aws> [ami_vtkjbi] Deleting node instance: nothing to do 2019-08-08 07:04:10.200 CFY <aws> [cloud_init_k8xkrm.stop] Task succeeded 'cloudify_cloudinit.tasks.update' 2019-08-08 07:04:10.345 CFY <aws> [nicdb_8id1l8] Deleting node instance 2019-08-08 07:04:10.623 CFY <aws> [nic2_ao90em.delete] Sending task 'cloudify_aws.ec2.resources.eni.delete' 2019-08-08 07:04:10.814 CFY <aws> [cloud_init_k8xkrm] Stopped node instance 2019-08-08 07:04:11.535 CFY <aws> [ami_vtkjbi] Deleted node instance 2019-08-08 07:04:11.632 CFY <aws> [nic1_vixg0u] Stopped node instance 2019-08-08 07:04:11.815 CFY <aws> [nicdb_8id1l8.delete] Sending task 'cloudify_aws.ec2.resources.eni.delete' 2019-08-08 07:04:12.199 CFY <aws> [cloud_initdb_nt7yiq] Relationships unlinked 2019-08-08 07:04:13.084 CFY <aws> [cloud_init2_e6blw1.delete] Task succeeded 'cloudify_cloudinit.tasks.update' 2019-08-08 07:04:13.155 CFY <aws> [cloud_init_k8xkrm] Unlinking relationships 2019-08-08 07:04:13.693 CFY <aws> [cloud_initdb_nt7yiq] Deleting node instance 2019-08-08 07:04:14.076 CFY <aws> [cloud_initdb_nt7yiq.delete] Sending task 'cloudify_cloudinit.tasks.update' 2019-08-08 07:04:14.661 CFY <aws> [cloud_init2_e6blw1] Deleted node instance 2019-08-08 07:04:14.912 CFY <aws> [cloud_init_k8xkrm] Relationships unlinked 2019-08-08 07:04:15.544 CFY <aws> [nic1_vixg0u] Unlinking relationships 2019-08-08 07:04:16.661 CFY <aws> [cloud_init_k8xkrm] Deleting node instance 2019-08-08 07:04:16.813 CFY <aws> [nic1_vixg0u] Relationships unlinked 2019-08-08 07:04:17.088 CFY <aws> [cloud_init_k8xkrm.delete] Sending task 'cloudify_cloudinit.tasks.update' 2019-08-08 07:04:18.235 CFY <aws> [nic1_vixg0u] Deleting node instance 2019-08-08 07:04:18.763 CFY <aws> [nic2_ao90em.delete] Task succeeded 'cloudify_aws.ec2.resources.eni.delete' 2019-08-08 07:04:18.872 CFY <aws> [nic2_ao90em] Deleted node instance 2019-08-08 07:04:19.017 CFY <aws> [cloud_initdb_nt7yiq.delete] Task succeeded 'cloudify_cloudinit.tasks.update' 2019-08-08 07:04:19.141 CFY <aws> [nic1_vixg0u.delete] Sending task 'cloudify_aws.ec2.resources.eni.delete' 2019-08-08 07:04:20.062 CFY <aws> [nicdb_8id1l8.delete] Task succeeded 'cloudify_aws.ec2.resources.eni.delete' 2019-08-08 07:04:20.521 CFY <aws> [nicdb_8id1l8] Deleted node instance 2019-08-08 07:04:20.781 CFY <aws> [cloud_initdb_nt7yiq] Deleted node instance 2019-08-08 07:04:22.091 CFY <aws> [cloud_init_k8xkrm.delete] Task succeeded 'cloudify_cloudinit.tasks.update' 2019-08-08 07:04:22.463 CFY <aws> [cloud_init_k8xkrm] Deleted node instance 2019-08-08 07:04:26.971 CFY <aws> [nic1_vixg0u.delete] Task succeeded 'cloudify_aws.ec2.resources.eni.delete' 2019-08-08 07:04:27.049 CFY <aws> [nic1_vixg0u] Deleted node instance 2019-08-08 07:04:27.962 CFY <aws> [subnet_hmle9w] Stopping node instance 2019-08-08 07:04:28.283 CFY <aws> [security_group_qe8gsj] Stopping node instance 2019-08-08 07:04:28.364 CFY <aws> [subnet_hmle9w] Validating node instance after deletion: nothing to do 2019-08-08 07:04:28.451 CFY <aws> [security_group_qe8gsj] Validating node instance after deletion: nothing to do 2019-08-08 07:04:28.544 CFY <aws> [subnet_hmle9w] Stopped node instance: nothing to do 2019-08-08 07:04:28.633 CFY <aws> [security_group_qe8gsj] Stopped node instance: nothing to do 2019-08-08 07:04:29.100 CFY <aws> [subnet_hmle9w] Unlinking relationships 2019-08-08 07:04:29.173 CFY <aws> [security_group_qe8gsj] Unlinking relationships 2019-08-08 07:04:29.522 CFY <aws> [security_group_qe8gsj] Relationships unlinked 2019-08-08 07:04:29.584 CFY <aws> [subnet_hmle9w] Relationships unlinked 2019-08-08 07:04:29.668 CFY <aws> [security_group_qe8gsj] Deleting node instance 2019-08-08 07:04:30.135 CFY <aws> [subnet_hmle9w] Deleting node instance 2019-08-08 07:04:30.443 CFY <aws> [security_group_qe8gsj.delete] Sending task 'cloudify_aws.ec2.resources.securitygroup.delete' 2019-08-08 07:04:31.578 CFY <aws> [subnet_hmle9w.delete] Sending task 'cloudify_aws.ec2.resources.subnet.delete' 2019-08-08 07:04:35.090 CFY <aws> [security_group_qe8gsj.delete] Task succeeded 'cloudify_aws.ec2.resources.securitygroup.delete' 2019-08-08 07:04:35.282 CFY <aws> [security_group_qe8gsj] Deleted node instance 2019-08-08 07:04:36.313 CFY <aws> [subnet_hmle9w.delete] Task succeeded 'cloudify_aws.ec2.resources.subnet.delete' 2019-08-08 07:04:36.543 CFY <aws> [subnet_hmle9w] Deleted node instance 2019-08-08 07:04:37.043 CFY <aws> [vpc_ghkka4] Stopping node instance 2019-08-08 07:04:37.291 CFY <aws> [vpc_ghkka4] Validating node instance after deletion: nothing to do 2019-08-08 07:04:37.362 CFY <aws> [vpc_ghkka4] Stopped node instance: nothing to do 2019-08-08 07:04:37.668 CFY <aws> [vpc_ghkka4] Unlinking relationships 2019-08-08 07:04:37.941 CFY <aws> [vpc_ghkka4] Relationships unlinked 2019-08-08 07:04:38.130 CFY <aws> [vpc_ghkka4] Deleting node instance 2019-08-08 07:04:38.482 CFY <aws> [vpc_ghkka4.delete] Sending task 'cloudify_aws.ec2.resources.vpc.delete' 2019-08-08 07:04:47.597 CFY <aws> [vpc_ghkka4.delete] Task succeeded 'cloudify_aws.ec2.resources.vpc.delete' 2019-08-08 07:04:47.987 CFY <aws> [vpc_ghkka4] Deleted node instance 2019-08-08 07:04:48.527 CFY <aws> 'uninstall' workflow execution succeeded Finished executing workflow uninstall on deployment aws cloudify common logs monitors play_test.sh README.md reset_test.sh results stop_test.sh temp_count temp_cpu_amount temp_io_amount temp_mem_amount temp_mem_initial temp_mem_total temp_monitor_pid temp_net_amount terraform Run 'cfy events list ed5745a4-0ec1-4ea6-acb3-dc9d57a1b142' to retrieve the execution's events/logs Trying to delete deployment aws... Deployment deleted Deleting blueprint cloudify-wordpress-blueprint-aws... Blueprint deleted Trying to delete deployment aws... An error occurred on the server: 404: Requested `Deployment` with ID `aws` was not found Deleting blueprint cloudify-wordpress-blueprint-aws... An error occurred on the server: 404: Requested `Blueprint` with ID `cloudify-wordpress-blueprint-aws` was not found'
